name: Python CI

on:
  push:
    paths:
      - '**.py'
      - '**.c'
      - '**.h'
      - '**.cpp'
      - '**.hpp'
      - '**.lock'
      - '**.toml'
      - '**.yaml'
      - '**.yml'
      - '**.ini'
    branches: [ master ]
  pull_request:
    paths:
      - '**.py'
      - '**.c'
      - '**.h'
      - '**.cpp'
      - '**.hpp'
      - '**.lock'
      - '**.toml'
      - '**.yaml'
      - '**.yml'
      - '**.ini'
    branches: [ master ]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        poetry-version: ["2.1.1"]
        os: [ubuntu-latest, macos-14, macos-latest]
    runs-on: ${{ matrix.os }}
#   checks should not take more than 10 minutes (including build and setup step).
#   If it is the case probably something heavy trespassed to unit tests.
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update CMake
        uses: jwlawson/actions-setup-cmake@v2.0
      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ matrix.poetry-version }}
          virtualenvs-create: true
          virtualenvs-in-project: true
      - run: (poetry build --no-interaction)
        env:
          DISABLE_ABC_CEXT: 1
          CMAKE_BUILD_PARALLEL_LEVEL: 8
      - run: (poetry install --no-interaction)
      - name: mypy
        if: always()
        run: poetry run mypy -p xyz
      - name: flake8
        if: always()
        run: poetry run flake8 xyz tests tools
      - name: pytest
        if: always()
        run: poetry run pytest tests -v -m 'not (manual or slow or ABC)'
      - name: usort
        if: always()
        run: poetry run usort check xyz tests tools
      - name: docformatter
        if: always()
        run: poetry run docformatter --check --diff xyz/ tests/ tools/
      - name: black
        if: always()
        run: poetry run black --check --diff xyz/ tests/ tools/